// Generated by scripts/sync-project-images.mjs — do not edit by hand.
// Add screenshots under public/images/projects/<slug>/ and this file catches up
// on the next `npm run dev` or `npm run build`.

export const projectImages: Record<string, string[]> = {
  "air-ecommerce": [
    "/images/projects/air-ecommerce/01.jpg",
  ],
  "airportiq": [
    "/images/projects/airportiq/01.png",
    "/images/projects/airportiq/02.png",
    "/images/projects/airportiq/03.png",
    "/images/projects/airportiq/04.png",
    "/images/projects/airportiq/05.png",
    "/images/projects/airportiq/06.png",
  ],
  "energym": [
    "/images/projects/energym/01.jpg",
  ],
  "nandina-smart-home": [
    "/images/projects/nandina-smart-home/01.jpg",
  ],
  "pumpiq": [
    "/images/projects/pumpiq/01.png",
    "/images/projects/pumpiq/02.png",
    "/images/projects/pumpiq/03.png",
    "/images/projects/pumpiq/04.png",
    "/images/projects/pumpiq/05.png",
    "/images/projects/pumpiq/06.png",
  ],
  "trashcans": [
    "/images/projects/trashcans/01.png",
    "/images/projects/trashcans/02.png",
    "/images/projects/trashcans/03.png",
    "/images/projects/trashcans/04.png",
  ],
};
