// Generated by scripts/sync-project-images.mjs — do not edit by hand.
// Add screenshots under public/images/projects/<slug>/ and this file catches up
// on the next `npm run dev` or `npm run build`.

export const projectImages: Record<string, string[]> = {
  "air-ecommerce": [
    "/images/projects/air-ecommerce/01.jpg",
  ],
  "energym": [
    "/images/projects/energym/01.jpg",
  ],
  "nandina-smart-home": [
    "/images/projects/nandina-smart-home/01.jpg",
  ],
};
